// Fixtures for the operator overview's top-spenders ledger — 18 rows, mixing accounts and
// projects on one ranking (the real production shape: an operator does not pre-split them), with
// an operator-scale spread from ~$4.2k down to ~$40 rather than a handful of round demo numbers.

import type { TopSpenderRow } from './types';

export const topSpendersFixture: TopSpenderRow[] = [
  {
    key: 'acct_acme',
    scope: 'account',
    name: 'acme-labs',
    spendMtd: 4218.62,
    delta: { direction: 'up', label: '22% vs prev period' },
    lastActiveLabel: '3 minutes ago',
  },
  {
    key: 'proj_northwind_gateway',
    scope: 'project',
    name: 'gateway-prod',
    account: 'northwind-ai',
    spendMtd: 3904.11,
    delta: { direction: 'up', label: '9% vs prev period' },
    lastActiveLabel: '11 minutes ago',
  },
  {
    key: 'acct_contoso',
    scope: 'account',
    name: 'contoso-data',
    spendMtd: 3120.4,
    delta: { direction: 'flat', label: 'no change' },
    lastActiveLabel: '48 minutes ago',
  },
  {
    key: 'proj_acme_batch',
    scope: 'project',
    name: 'ingest-batch',
    account: 'acme-labs',
    spendMtd: 2860.75,
    delta: { direction: 'down', label: '6% vs prev period' },
    lastActiveLabel: '2 hours ago',
  },
  {
    key: 'acct_globex',
    scope: 'account',
    name: 'globex-research',
    spendMtd: 2402.18,
    delta: { direction: 'up', label: '31% vs prev period' },
    lastActiveLabel: '19 minutes ago',
  },
  {
    key: 'acct_initech',
    scope: 'account',
    name: 'initech-core',
    spendMtd: 1875.3,
    delta: { direction: 'up', label: '4% vs prev period' },
    lastActiveLabel: '1 hour ago',
  },
  {
    key: 'proj_fabrikam_ml',
    scope: 'project',
    name: 'model-serving',
    account: 'fabrikam-ml',
    spendMtd: 1640.02,
    delta: { direction: 'down', label: '14% vs prev period' },
    lastActiveLabel: '5 hours ago',
  },
  {
    key: 'acct_wayne',
    scope: 'account',
    name: 'wayne-analytics',
    spendMtd: 1288.55,
    delta: { direction: 'flat', label: 'no change' },
    lastActiveLabel: '3 hours ago',
  },
  {
    key: 'proj_stark_infer',
    scope: 'project',
    name: 'inference-edge',
    account: 'stark-infer',
    spendMtd: 964.2,
    delta: { direction: 'up', label: '58% vs prev period' },
    lastActiveLabel: '27 minutes ago',
  },
  {
    key: 'acct_umbrella',
    scope: 'account',
    name: 'umbrella-platform',
    spendMtd: 812.4,
    delta: { direction: 'down', label: '3% vs prev period' },
    lastActiveLabel: '9 hours ago',
  },
  {
    key: 'proj_hooli_playground',
    scope: 'project',
    name: 'playground',
    account: 'hooli',
    spendMtd: 601.86,
    delta: { direction: 'up', label: '12% vs prev period' },
    lastActiveLabel: '14 hours ago',
  },
  {
    key: 'acct_soylent',
    scope: 'account',
    name: 'soylent-infra',
    spendMtd: 455.7,
    delta: { direction: 'flat', label: 'no change' },
    lastActiveLabel: '1 day ago',
  },
  {
    key: 'acct_massive',
    scope: 'account',
    name: 'massive-dynamic',
    spendMtd: 340.15,
    delta: { direction: 'down', label: '21% vs prev period' },
    lastActiveLabel: '2 days ago',
  },
  {
    key: 'proj_pied_piper_compress',
    scope: 'project',
    name: 'compression-api',
    account: 'pied-piper',
    spendMtd: 288.9,
    delta: { direction: 'up', label: '7% vs prev period' },
    lastActiveLabel: '4 hours ago',
  },
  {
    key: 'acct_aviato',
    scope: 'account',
    name: 'aviato',
    spendMtd: 176.3,
    delta: { direction: 'up', label: '46% vs prev period' },
    lastActiveLabel: '6 hours ago',
  },
  {
    key: 'proj_dunder_reports',
    scope: 'project',
    name: 'reporting',
    account: 'dunder-mifflin',
    spendMtd: 118.44,
    delta: { direction: 'flat', label: 'no change' },
    lastActiveLabel: '3 days ago',
  },
  {
    key: 'acct_gringotts',
    scope: 'account',
    name: 'gringotts-labs',
    spendMtd: 72.05,
    delta: { direction: 'down', label: '9% vs prev period' },
    lastActiveLabel: '5 days ago',
  },
  {
    key: 'acct_oceanic',
    scope: 'account',
    name: 'oceanic-systems',
    spendMtd: 41.18,
    delta: { direction: 'up', label: '210% vs prev period' },
    lastActiveLabel: '9 days ago',
  },
];

/** Genuinely queried and empty — a real, wired, empty answer, never a permanent placeholder. */
export const topSpendersEmpty: TopSpenderRow[] = [];
