#!/usr/bin/env node
// Generates packages/authz-rpc/generated/{models,inputs,sdk}.ts from schema/authz.cstack.
// Run via `pnpm --filter @lightbridge/authz-rpc codegen` (wired into the workspace-wide
// `codegen:all` / `postinstall`). Output is gitignored — regenerate, don't hand-edit.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseCstack } from './parse-cstack.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(HERE, '../schema/authz.cstack');
const OUT_DIR = resolve(HERE, '../generated');

// Relation-target-only per the schema's own doc comment: no `id` column, composite PK,
// never meant to be fetched/mutated directly by clients — exists solely for `@@allow`
// policy traversal on Account/Project/ApiKey. Excluded from client-visible generation.
const EXCLUDE_MODELS = new Set(['AccountMembership']);

const SCALARS = {
  Cuid: 'string',
  String: 'string',
  DateTime: 'string',
  Boolean: 'boolean',
  Int: 'number',
  Float: 'number',
  Json: 'JsonValue',
};

function tsScalar(field) {
  const base = SCALARS[field.scalarType];
  if (!base) {
    throw new Error(`generate: unknown scalar type "${field.scalarType}" (field "${field.name}")`);
  }
  return field.isArray ? `${base}[]` : base;
}

const hasMod = (field, name) => field.modifiers.some((m) => m.name === name);
const isServerOnly = (f) => hasMod(f, 'server_only');
const isReadonlyField = (f) => hasMod(f, 'readonly');
const hasDefault = (f) => hasMod(f, 'default');
const isId = (f) => hasMod(f, 'id');

function scalarFields(model) {
  return model.fields.filter((f) => !f.isRelation);
}

/** Verb -> whether `@@allow("<verb>", ...)` is declared on the model. */
function allowMap(model) {
  const verbs = { create: false, read: false, update: false, delete: false };
  for (const attr of model.attrs) {
    if (attr.name !== 'allow' || !attr.args) continue;
    const m = attr.args.match(/^\s*"(\w+)"/);
    if (m && m[1] in verbs) verbs[m[1]] = true;
  }
  return verbs;
}

function emitInterface(name, fields, doc) {
  const lines = fields.map((f) => `  ${f.name}${f.optional ? '?' : ''}: ${tsScalar(f)};`);
  const docComment = doc ? `/** ${doc} */\n` : '';
  return `${docComment}export interface ${name} {\n${lines.join('\n')}\n}`;
}

function createInputFields(model) {
  return scalarFields(model).filter(
    (f) => !isServerOnly(f) && !isReadonlyField(f) && !hasDefault(f)
  );
}

function updateInputFields(model) {
  return scalarFields(model)
    .filter((f) => !isServerOnly(f) && !isReadonlyField(f) && !hasDefault(f) && !isId(f))
    .map((f) => ({ ...f, optional: true }));
}

function readModelFields(model) {
  return scalarFields(model).filter((f) => !isServerOnly(f));
}

function main() {
  const source = readFileSync(SCHEMA_PATH, 'utf8');
  const ast = parseCstack(source);

  const modelNames = Object.keys(ast.models).filter((name) => !EXCLUDE_MODELS.has(name));

  // ---------------------------------------------------------------- models.ts
  const modelInterfaces = modelNames.map((name) =>
    emitInterface(name, readModelFields(ast.models[name]))
  );
  const typeInterfaces = Object.keys(ast.types).map((name) =>
    emitInterface(name, ast.types[name].fields)
  );

  const modelsTs = [
    '// AUTO-GENERATED by packages/authz-rpc/codegen/generate.mjs from schema/authz.cstack.',
    '// Do not edit by hand — re-run `pnpm --filter @lightbridge/authz-rpc codegen`.',
    "import type { JsonValue } from '../src/value';",
    '',
    ...modelInterfaces,
    '',
    ...typeInterfaces,
    '',
  ].join('\n\n');

  // ---------------------------------------------------------------- inputs.ts
  const createInterfaces = [];
  const updateInterfaces = [];
  const allowByModel = {};
  for (const name of modelNames) {
    const model = ast.models[name];
    const allow = allowMap(model);
    allowByModel[name] = allow;
    if (allow.create) {
      createInterfaces.push(emitInterface(`Create${name}Input`, createInputFields(model)));
    }
    if (allow.update) {
      updateInterfaces.push(emitInterface(`Update${name}Input`, updateInputFields(model)));
    }
  }

  const inputsTs = [
    '// AUTO-GENERATED by packages/authz-rpc/codegen/generate.mjs from schema/authz.cstack.',
    '// Do not edit by hand — re-run `pnpm --filter @lightbridge/authz-rpc codegen`.',
    "import type { JsonValue } from '../src/value';",
    '',
    ...createInterfaces,
    '',
    ...updateInterfaces,
    '',
  ].join('\n\n');

  // ---------------------------------------------------------------- sdk.ts
  const modelTypeNames = modelNames.filter((name) => ast.models[name]); // CRUD models only
  const sdkParts = [];

  for (const name of modelTypeNames) {
    const model = ast.models[name];
    const allow = allowByModel[name];
    const jsonFields = scalarFields(model).filter(
      (f) => f.scalarType === 'Json' && !isServerOnly(f)
    );
    const opId = (verb) => `model.${name}.${verb}`;

    // Tag/untag helpers operate on plain `Record<string, unknown>` — generated model/input
    // interfaces have no index signature, so the two casts at each call site are an
    // intentional double-assertion boundary (`as unknown as X`), not a type-safety gap:
    // the fields being reshaped (the Json-typed ones) are known-present on both sides.
    if (jsonFields.length > 0) {
      const fieldNames = jsonFields.map((f) => f.name);
      sdkParts.push(
        [
          `function tag${name}Fields(input: Record<string, unknown>): Record<string, unknown> {`,
          '  const out = { ...input };',
          ...fieldNames.map(
            (n) => `  if (out.${n} !== undefined) out.${n} = tagValue(out.${n} as JsonValue);`
          ),
          '  return out;',
          '}',
        ].join('\n')
      );
      sdkParts.push(
        [
          `function untag${name}Fields(entity: Record<string, unknown>): Record<string, unknown> {`,
          '  const out = { ...entity };',
          ...fieldNames.map(
            (n) =>
              `  if (out.${n} !== undefined && out.${n} !== null) out.${n} = untagValue(out.${n});`
          ),
          '  return out;',
          '}',
        ].join('\n')
      );
    }

    const toRecord = (expr) => `(${expr} as unknown as Record<string, unknown>)`;
    const wrapOut = (expr) =>
      jsonFields.length > 0
        ? `(untag${name}Fields(${toRecord(expr)}) as unknown as ${name})`
        : expr;
    const wrapIn = (expr) => (jsonFields.length > 0 ? `tag${name}Fields(${toRecord(expr)})` : expr);

    if (allow.read) {
      sdkParts.push(
        [
          `export async function list${name}s(params: ListParams = {}): Promise<${name}[]> {`,
          `  const items = await rpcCall<${name}[]>('${opId('list')}', listInput(params));`,
          jsonFields.length > 0
            ? `  return items.map((item) => ${wrapOut('item')});`
            : '  return items;',
          '}',
        ].join('\n')
      );
      sdkParts.push(
        [
          `export async function get${name}(id: string): Promise<${name}> {`,
          `  const item = await rpcCall<${name}>('${opId('get')}', { id });`,
          `  return ${wrapOut('item')};`,
          '}',
        ].join('\n')
      );
    }
    if (allow.create) {
      sdkParts.push(
        [
          `export async function create${name}(input: Create${name}Input): Promise<${name}> {`,
          `  const item = await rpcCall<${name}>('${opId('create')}', ${wrapIn('input')});`,
          `  return ${wrapOut('item')};`,
          '}',
        ].join('\n')
      );
    }
    if (allow.update) {
      sdkParts.push(
        [
          `export async function update${name}(id: string, patch: Update${name}Input): Promise<${name}> {`,
          `  const item = await rpcCall<${name}>('${opId('update')}', { id, patch: ${wrapIn('patch')} });`,
          `  return ${wrapOut('item')};`,
          '}',
        ].join('\n')
      );
    }
    if (allow.delete) {
      sdkParts.push(
        [
          `export async function delete${name}(id: string): Promise<${name}> {`,
          `  const item = await rpcCall<${name}>('${opId('delete')}', { id });`,
          `  return ${wrapOut('item')};`,
          '}',
        ].join('\n')
      );
    }
  }

  for (const proc of ast.procedures) {
    sdkParts.push(
      [
        `export function ${proc.name}(args: ${proc.argsType}): Promise<${proc.returnType}> {`,
        `  return rpcCall('procedure.${proc.name}', { args });`,
        '}',
      ].join('\n')
    );
  }

  const inputImportNames = [];
  for (const name of modelTypeNames) {
    if (allowByModel[name].create) inputImportNames.push(`Create${name}Input`);
    if (allowByModel[name].update) inputImportNames.push(`Update${name}Input`);
  }
  const procedureTypeImports = new Set();
  for (const proc of ast.procedures) {
    procedureTypeImports.add(proc.argsType);
    procedureTypeImports.add(proc.returnType);
  }
  // Everything importable from models.ts: the CRUD models themselves, plus every `type`
  // block procedures reference (procedure args/return types not already a CRUD model).
  const modelsImportNames = [...new Set([...modelTypeNames, ...procedureTypeImports])].filter(
    (t) => modelTypeNames.includes(t) || ast.types[t]
  );

  const sdkTs = [
    '// AUTO-GENERATED by packages/authz-rpc/codegen/generate.mjs from schema/authz.cstack.',
    '// Do not edit by hand — re-run `pnpm --filter @lightbridge/authz-rpc codegen`.',
    "import { rpcCall } from '../src/transport';",
    "import { tagValue, untagValue, type JsonValue } from '../src/value';",
    `import type { ${modelsImportNames.join(', ')} } from './models';`,
    inputImportNames.length > 0
      ? `import type { ${inputImportNames.join(', ')} } from './inputs';`
      : null,
    '',
    'export type ListFilter = { key: string; value: string };',
    'export type ListParams = { limit?: number; offset?: number; filters?: ListFilter[] };',
    '',
    'function listInput(params: ListParams) {',
    '  return { limit: params.limit, offset: params.offset, filters: params.filters };',
    '}',
    '',
    ...sdkParts,
    '',
  ]
    .filter((line) => line !== null)
    .join('\n\n');

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(resolve(OUT_DIR, 'models.ts'), `${modelsTs}\n`);
  writeFileSync(resolve(OUT_DIR, 'inputs.ts'), `${inputsTs}\n`);
  writeFileSync(resolve(OUT_DIR, 'sdk.ts'), `${sdkTs}\n`);

  console.log(
    `authz-rpc codegen: wrote models.ts (${modelInterfaces.length} models, ${typeInterfaces.length} types), ` +
      `inputs.ts (${createInterfaces.length} create, ${updateInterfaces.length} update), ` +
      `sdk.ts (${sdkParts.length} exports) to ${OUT_DIR}`
  );
}

main();
