import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { StorybookConfig } from '@storybook/react-vite';

const HERE = dirname(fileURLToPath(import.meta.url));
const LCI_SRC = resolve(HERE, '../../../apps/lci/src');
const stub = (name: string) => join(HERE, 'lci-stubs', name);

/**
 * `apps/lci` modules that only exist inside a running Next.js server, mapped to their Storybook
 * substitute. The three `*-actions` files are Server Actions (`'use server'`, `next/cache`) and
 * `lib/server/session` reads the httpOnly cookie — all four transitively pull `next/headers`,
 * `openid-client` and `jose`, none of which can be bundled for a browser.
 *
 * Keyed by extensionless absolute path, because that is what a relative import resolves to.
 */
const SERVER_STUBS = new Map(
  [
    'containers/admin-actions',
    'containers/repository-actions',
    'containers/repository-settings-actions',
    'lib/server/session',
  ].map((module) => [join(LCI_SRC, module), stub('lci-server.ts')])
);

const config: StorybookConfig = {
  // Two story roots, one Storybook.
  //
  // `apps/lci`'s screens stay in `apps/lci` — ADR 0014 and `docs/design/lci-app/PRIMITIVES.md`
  // classify them as app-local (the code graph explicitly so), and nothing about wanting them in
  // the sidebar changes that. Moving them into `ui-web` would also invert the dependency: `lci`
  // depends on `ui-web`, not the other way round. So the STORIES live next to the screens and this
  // config reaches out for them; only the reverse (a `ui-web` module importing `apps/lci`) would
  // be a cycle, and nothing here does that.
  //
  // `theme.css` already `@source`s `apps/lci/src`, so the utility classes those screens use are
  // generated by this Storybook's own Tailwind pass with no further wiring.
  stories: ['../src/**/*.stories.@(ts|tsx)', '../../../apps/lci/src/**/*.stories.@(ts|tsx)'],
  addons: ['@storybook/addon-a11y'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  typescript: {
    // Plain DOM components with hand-written prop types — none of packages/ui's
    // React Native docgen fights, but skip it anyway: this package has no need
    // for auto-generated prop tables and it's one less thing that can choke on
    // a CVA variant type.
    reactDocgen: false,
  },
  viteFinal(viteConfig) {
    // `next/link` and `next/navigation` are bare specifiers, so a plain alias reaches them.
    // `useRouter()` THROWS without the App Router context — this is not a soft failure a story
    // decorator could paper over, which is why it is aliased rather than mocked.
    //
    // Nothing in `packages/ui-web` imports either one (ADR 0017: `ui-web` is framework-agnostic
    // and "Storybook renders it with no app around it"), so these aliases only ever bite on
    // `apps/lci` modules.
    viteConfig.resolve = viteConfig.resolve ?? {};
    viteConfig.resolve.alias = [
      ...(Array.isArray(viteConfig.resolve.alias) ? viteConfig.resolve.alias : []),
      { find: /^next\/link$/, replacement: stub('next-link.tsx') },
      { find: /^next\/navigation$/, replacement: stub('next-navigation.ts') },
      // `apps/lci` imports this package by its deep subpath (`@lightbridge/ui-web/src/…`), which
      // this package's `exports` map answers with a DIRECTORY (`"./src/*": "./src/*"`). Next and
      // Vitest both fall back to directory-index resolution there; Rollup does not — it fails the
      // build with "failed to resolve import … from apps/lci/…". Aliasing the specifier straight
      // at the source tree hands it back to Vite's ordinary extension/index resolution, which is
      // what every `packages/ui-web` story already goes through with its relative imports.
      { find: /^@lightbridge\/ui-web\/src\//, replacement: `${resolve(HERE, '../src')}/` },
      { find: /^@lightbridge\/ui-web$/, replacement: resolve(HERE, '../src/index.ts') },
    ];

    // The server modules are imported RELATIVELY (`./admin-actions`, `../lib/server/session`), and
    // Vite's alias plugin matches the raw specifier, never the resolved path — so a path-keyed
    // alias would silently never fire. Resolving the specifier against its importer first is the
    // only way to catch them.
    viteConfig.plugins = viteConfig.plugins ?? [];
    viteConfig.plugins.push({
      name: 'lci-storybook-server-stubs',
      enforce: 'pre',
      resolveId(source: string, importer: string | undefined) {
        if (!importer || !source.startsWith('.')) return null;
        return SERVER_STUBS.get(resolve(dirname(importer), source)) ?? null;
      },
    });

    return viteConfig;
  },
};

export default config;
