#!/bin/sh
set -eu

template="/usr/share/nginx/html/config.template.json"
output="/usr/share/nginx/html/config.json"

if [ -f "$template" ]; then
  envsubst '${EXPO_PUBLIC_BACKEND_URL} ${EXPO_PUBLIC_API_BASE_PATH} ${EXPO_PUBLIC_BUDGET_URL} ${EXPO_PUBLIC_USAGE_URL} ${EXPO_PUBLIC_GATEWAY_URL} ${EXPO_PUBLIC_ANALYTICS_URL} ${EXPO_PUBLIC_KEYCLOAK_ISSUER} ${EXPO_PUBLIC_KEYCLOAK_CLIENT_ID} ${EXPO_PUBLIC_KEYCLOAK_SCHEME} ${EXPO_PUBLIC_KEYCLOAK_EXPECTED_AUDIENCE} ${EXPO_PUBLIC_KEYCLOAK_AUDIENCE_REQUIRED} ${EXPO_PUBLIC_GRAFANA_URL} ${EXPO_PUBLIC_GRAFANA_USAGE_DASHBOARD_PATH} ${EXPO_PUBLIC_LOGO_URL}' < "$template" > "$output"
fi
